### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by fabb**
:warning: This is not meant for merging, just to serve as a discussion thread on GitHub.

This is still work in progress, the tests for the reactive part are still to do, I'm on it.

My motivation was that the reactive version contained some bugs (#3), and as a learning project I wanted to write some tests to compare the imperative and reactive versions. This needed a **lot** of refactoring in order to abstract the gesture recognizer and timer interaction away.
Unfortunately now the implementation has become quite big. I guess that is the price to pay for having proof that the implementation works as expected?

I'd love to hear suggestions and feedback/contributions. I didn't merge in the latest changes from #2 for now, as it would complicate things more. Currently I'm starting to write the tests for the reactive part.

### CODE REVIEW

**Comment by almostintuitive** [comment]
🙌
cool, let's do this!!

I'll have a through look in the evening and come back with comments, thanks a lot!

it would be nice to merge this in at some point for sure though, I'm happy to take care of the conflicts to make both this and @morgz 's pull request work together somehow.

**Comment by fabb** [comment]
I created a common interface for the imperative and the reactive version, `GestureReactor`.
Unfortunately this meant that I could no longer directly use the `rx_event` on the gesture recognizers, but had to receive the pan/pinch gesture events via functions and modify an Rx `Variable` with them in order to get to the reactive world.
I guess without the restriction of having a common interface for both the imperative and the reactive version, it would be simpler possible to just pass two `Observables` to the initializer. Maybe I'll do that later on.

**Comment by fabb** [comment]
btw, I'm @klangwabe from twitter

**Comment by almostintuitive** [comment]
Looks really good, to be honest I'm not sure what I can add here:).

By the way, it feels like this is MVVM (although you'd probably not pass anything UIKit related down there). Which is super nice, I found it the only way to actually unit test the UI.

And the best part is that the test revealed that the original code is wrong on a few levels:).
I'll try to go through all the failures that I can reproduce.

By the way, would it make sense to create one helper class that's shared between the both unit test classes, that you just pass a properly configured GestureReactor and then it'll run all the tests? So you can get rid of lots of duplicated code in ImperativeGestureReactorTests and ReactiveGestureReactorTests. What do you think?

Also one super small thing that may be helpful - not necessarily here, but in other projects - is that you don't have to subclass NSObject in order to interact with NSTimer and stuff like that.
You have a comment here:
    // cannot be private due to use of target-action

but you could just use:
    @objc private func tick()

**Comment by fabb** [comment]
> @objc private func tick()
> Ah, nice tip. Committed the change.

**Comment by fabb** [comment]
> By the way, would it make sense to create one helper class that's shared between the both unit test classes, that you just pass a properly configured GestureReactor and then it'll run all the tests? So you can get rid of lots of duplicated code in ImperativeGestureReactorTests and ReactiveGestureReactorTests. What do you think?

I don't know. Could you sketch-code a solution? I thought about it too, but having helper functions in unit tests will show unit test assertion failures in the according line in the helper function, which makes it hard to track down which unit test was causing it. Plus, in a real project, I wouldn't have 2 different implementations.

**Comment by fabb** [comment]
ok, i merged the changes from master in, but i still have to use the ReactiveGestureReactor for the ReactiveViewController

**Comment by fabb** [comment]
Ok @itchingpixels, these are the open problems with the reactive versions:
- If one gesture recognizer starts and ends, and then the other starts, the timer is started, but it should not (`testBeganPanEndedPanBeganRotateGesture`)
- The last `Tick` and `Completed` happen immediately after each other, in the imperative version there is a second time between
- The timer counts up, not down like the imperative version
- It leaks (#5), maybe we can unit test this via `RxSwift.resourceCount`

Currently 2 problems exist with the unit tests:
- Cannot use `Variable` for `MockReactiveTimer`, as `Variable` sends the first value immediately, but we need it to wait until the first call to `mockExecuteOnTick` (I asked at the RxSwift project for some advice on this https://github.com/ReactiveX/RxSwift/issues/490)
- Cannot use `XCTAssertNil(mockTimer)` at the moment, as we need to retain the `mockTimer`, as it is not directly provided as `Observable` to the `sut`

**Comment by almostintuitive** [comment]
👍I'm happy to merge this in, I'm wondering if we should retain a copy of the "simpler" version, even if it's buggy, just for reference. Maybe in a different class, like SimplisticReactiveViewController?

what do you think?

**Comment by fabb** [comment]
Yes, definitely! Maybe also from the Imperative version. I also plan to create an additional testable Short Reactive version once the current unit test problems have been resolved.

**Comment by almostintuitive** [comment]
@fabb : what do you think about using the skip operator on Variable? just after .asObserverable() ?
not sure if it's the nicest solution ever though.

**Comment by almostintuitive** [comment]
I'll merge this in now, so we can merge in the other fix and work from there!
Feel free to push straight into this repo if you like @fabb !

**Comment by almostintuitive** [comment]
I'll copy over your list to an issue so we can continue the discussion!

**Comment by fabb** [comment]
Great, thank you!

**Pull request merged**
